// Code generated by avro/gen. DO NOT EDIT.
package model

import (
	_ "embed"
	"time"
)

//go:embed figchain.avsc
var Schema string

// Condition is a generated struct.
type Condition struct {
	Variable string   `avro:"variable"`
	Operator string   `avro:"operator"`
	Values   []string `avro:"values"`
}

// Rule is a generated struct.
type Rule struct {
	Description   *string     `avro:"description"`
	Conditions    []Condition `avro:"conditions"`
	TargetVersion string      `avro:"targetVersion"`
}

// FigDefinition is a generated struct.
type FigDefinition struct {
	Namespace     string    `avro:"namespace"`
	Key           string    `avro:"key"`
	FigID         string    `avro:"figId"`
	SchemaURI     string    `avro:"schemaUri"`
	SchemaVersion string    `avro:"schemaVersion"`
	CreatedAt     time.Time `avro:"createdAt"`
	UpdatedAt     time.Time `avro:"updatedAt"`
}

// Fig is a generated struct.
type Fig struct {
	FigID   string `avro:"figId"`
	Version string `avro:"version"`
	Payload []byte `avro:"payload"`
}

// FigFamily is a generated struct.
type FigFamily struct {
	Definition     FigDefinition `avro:"definition"`
	Figs           []Fig         `avro:"figs"`
	Rules          []Rule        `avro:"rules"`
	DefaultVersion *string       `avro:"defaultVersion"`
}

// InitialFetchRequest is a generated struct.
type InitialFetchRequest struct {
	Namespace     string     `avro:"namespace"`
	EnvironmentID string     `avro:"environmentId"`
	AsOfTimestamp *time.Time `avro:"asOfTimestamp"`
}

// InitialFetchResponse is a generated struct.
type InitialFetchResponse struct {
	FigFamilies   []FigFamily `avro:"figFamilies"`
	Cursor        string      `avro:"cursor"`
	EnvironmentID string      `avro:"environmentId"`
}

// UpdateFetchRequest is a generated struct.
type UpdateFetchRequest struct {
	Namespace     string `avro:"namespace"`
	Cursor        string `avro:"cursor"`
	EnvironmentID string `avro:"environmentId"`
}

// UpdateFetchResponse is a generated struct.
type UpdateFetchResponse struct {
	FigFamilies []FigFamily `avro:"figFamilies"`
	Cursor      string      `avro:"cursor"`
}
